name: smartdeck_prokit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  #Smart Deck
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.0
  country_code_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_icons:
  android: true
  ios: true
  image_path: "images/smartDeck/images/sdlogo.png"

flutter:

  uses-material-design: true

  assets:
    - images/smartDeck/images/
