name: wallet_app_prokit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.5
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.0.0

  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # Wallet App
  cached_network_image: ^3.2.3
  fl_chart: ^0.63.0

  dots_indicator: ^3.0.0
  scan: 1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.5

dependency_overrides:

  intl: ^0.17.0-nullsafety.2
  cached_network_image: 3.0.0
  http: ^0.13.0

flutter:

  uses-material-design: true

  assets:
   - images/walletApp/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

