name: beauty_master
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Base
  nb_utils: ^6.0.4
  intl: ^0.18.1

  # Common
  url_launcher: ^6.1.14
  http: ^1.1.0
  html: ^0.15.4

  # IMAGES & FONTS ICONS
  cupertino_icons: ^1.0.6
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0

  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  # MAP
  google_maps_flutter: ^2.5.0

  # UI
  flutter_svg: ^2.0.7

dependency_overrides:
  connectivity_plus: ^4.0.2
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter:

  uses-material-design: true

  assets:
    - fonts/
    - images/
