name: dating_prokit
description: A new Flutter project.
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.6
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0


  #Dating App
  cached_network_image: ^3.3.0
  multi_image_picker: ^4.8.1
  photo_view: ^0.14.0
  card_swiper: ^3.0.1

dependency_overrides:
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/

