name: cloudstorage_prokit
description: A new Flutter project.
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #API calling
  http: ^1.0.0

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.0.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  cached_network_image: ^3.2.3

  # Cloud Storage
  image_picker: ^0.8.1+3
  share: ^2.0.4
  multi_image_picker: ^4.8.00
  package_info: ^2.0.2
  url_launcher: ^6.1.11
  pointycastle: ^3.7.3
#  livestream: 1.0.1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true
  assets:
    - images/

